spring.application.name=springboot-web

server.port=8080

# Configuración personalizada para inyectar valores a atributos en el controlador
config.code=23232
config.username=jesusbeb
config.message=Hola desde el application.properties
config.listOfValues=valor1,valor2,valor3
config.message2=Otro mensaje desde el application.properties inyectado en el metodo values() del controlador PathVariableController